### ISSUE TITLE
missing comments

### ISSUE THREAD

**Issue by gour** [okin/nikola-theme-foundation6#7]
I've noticed that Disqus comments are not displayed in theme and tried by adding:

```
    ${helper.html_tags(post)}
    ${helper.html_pager(post)}
    % if not post.meta('nocomments') and site_has_comments:
        ${comments.comment_form(post.permalink(absolute=True), post.title(), post._base_path)}
    % endif
    ${comments.comment_link_script()}
```

by the end of _post.tmpl_, but I'm not sure what would be the right place?

**Comment by okin** [comment]
The place looks right to me.

I removed the comments sections because I do not have a site that uses it but feel free to do a PR.
